// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhthypiomvxwnayopagt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVodGh5cGlvbXZ4d25heW9wYWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2Njc4OTcsImV4cCI6MjA1NzI0Mzg5N30.s0v_u7I678W0hZlR3hvldVy3dbhJkObvTlgZ24xzkMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);